name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION

categories:
- title: 🛸 Breaking Changes
  labels:
  - breaking
- title: 🚀 New Features
  labels:
  - feature
- title: 🐞 BIGBUG Fixes
  labels:
  - BIGBUG
- title: 🐛 Bug Fixes
  labels:
  - bug
- title: 🌳 Dependencies
  labels:
  - dependencies

version-resolver:
  major:
    labels:
    - breaking
  minor:
    labels:
    - feature
  patch:
    labels:
    - BIGBUG
    - bug
    - dependencies

template: |
  ## Changes

  $CHANGES
