name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'

version-resolver:
  major:
    labels:
    - 'major'
  minor:
    labels:
    - 'minor'
  patch:
    labels:
    - 'patch'

template: |
  ## Changes

  $CHANGES