name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION

categories:
- title: '🐞 BIGBUG'
  labels:
  - 'BIGBUG'
- title: '🐛 Bug'
  labels:
  - 'bug'
- title: '🚀 Feature'
  labels:
  - 'feature'


version-resolver:
  major:
    labels:
    - major
  minor:
    labels:
    - minor
  patch:
    labels:
    - patch

template: |
  ## Changes

  $CHANGES