name-template: $RESOLVED_VERSION
tag-template: $RESOLVED_VERSION

categories:
- title: '🚀 Features'
  labels:
  - 'feature'
- title: '🐛 Bugs'
  labels:
  - 'bug'

version-resolver:
  major:
    labels:
    - major
  minor:
    labels:
    - minor
  patch:
    labels:
    - patch

template: |
  ## Changes

  $CHANGES