name: Release

on:
  push:
    branches:
    - master

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set current date
      id: set-current-date
      run: echo "::set-output name=current-date::$(Get-Date -Format yyyyMMdd)"

    - name: Publish S2VX.Desktop
      run: |
        cd S2VX.Desktop
        dotnet publish -p:PublishProfile=win-x64
        Compress-Archive -Path ./Stories, ./bin/Release/netcoreapp3.1/publish/S2VX.exe -DestinationPath ./S2VX.zip

    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.set-current-date.outputs.current-date }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./S2VX.zip
        asset_name: S2VX.zip
        asset_content_type: application/zip
