name: Publish GitHub release and artifact

on:
  push:
    branches:
    - release

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish S2VX.Desktop
      run: |
        cd S2VX.Desktop
        dotnet publish -p:PublishProfile=win-x64
        zip -j S2VX.zip bin/Release/netcoreapp3.1/publish/S2VX.exe
        zip -r S2VX.zip Stories

    - name: Publish release to GitHub
      id: release-drafter
      uses: release-drafter/release-drafter@v5
      with:
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.release-drafter.outputs.upload_url }}
        asset_path: ./S2VX.Desktop/S2VX.zip
        asset_name: S2VX.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Release must have Release in title
      if: ${{ github.head_ref == 'release' }}
      uses: deepakputhraya/action-pr-title@master
      with:
        allowed_prefixes: 'Release'
        prefix_case_sensitive: true
