name: Release

on: push

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set current date
      run: echo "CURRENT_DATE=$(Get-Date -Format yyyy/MM/dd)" >> $GITHUB_ENV

    - name: Echo 1
      run: echo $CURRENT_DATE

    - name: Echo 2
      run: echo ${{ env.CURRENT_DATE }}
