name: Release

on: push

jobs:
  release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set current date
      id: set-current-date
      run: echo "::set-output name=current-date::$(Get-Date -Format yyyy/MM/dd)"

    - name: Echo 1
      run: echo ${{ steps.set-current-date.outputs.current-date }}
