name: Validate pull request rules

on:
  pull_request:
    types:
    - opened
    - labeled
    - unlabeled
    - synchronize
    - edited

jobs:
  validate-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Release cannot be source branch
      if: ${{ github.head_ref == 'release' }}
      run: exit error

    - name: Master cannot merge to feature branches
      if: ${{ github.head_ref == 'master' && github.base_ref != 'release' }}
      run: exit error

    - name: Feature branches cannot merge to release
      if: ${{ github.head_ref != 'release' && github.head_ref != 'master' && github.base_ref == 'release' }}
      run: exit error

    - name: Pull requests must have a label
      uses: mheap/github-action-required-labels@v1
      with:
        mode: exactly
        count: 1
        labels: breaking, feature, BIGBUG, bug, dependencies

    - name: Pull requests must link an issue
      if: ${{ contains(github.event.issue.labels.*.name, 'dependencies') == false }}
      uses: hattan/verify-linked-issue-action@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Release must have Release in title
      if: ${{ github.base_ref == 'release' }}
      uses: deepakputhraya/action-pr-title@master
      with:
        allowed_prefixes: Release
        prefix_case_sensitive: true
